name: login_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik_regular.ttf
          weight: 400
        - asset: fonts/rubik_medium.ttf
          weight: 500
